image: node:lts
before_script:
  - npm install
pages:
  script:
    - export NODE_ENV=production
    - export NEXT_PUBLIC_BASE_PATH=carlos
    - npm run-script build
    - rm -rf public/*
    - mv out/* public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
